/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ams.ggc.struts;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import ams.ggc.business.NewsBusinessManager;
import ams.ggc.common.*;
import ams.ggc.common.NEWS.NewsDAOInterface;
import ams.ggc.common.NEWS.NewsENT;
import ams.ggc.common.NEWS.NewsLST;
import ams.ggc.common.tools.AMSException;
import ams.ggc.common.tools.NVL;


/** 
 * MyEclipse Struts
 * Creation date: 09-21-2010
 * 
 * XDoclet definition:
 * @struts.action parameter="reqCode" validate="true"
 * @struts.action-forward name="list" path="/jsp/farsi/news/newsList.jsp"
 */
public class NewsAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ActionForward af = null;
		String reqCode=request.getParameter("reqCode");	
		if("miniList".equalsIgnoreCase(reqCode)){
			NewsLST lst = new NewsLST();
			try {
				lst = getDAO().getNewsMiniLST(request.getParameter("language"));
			} catch (AMSException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			request.setAttribute("newsMiniLST", lst);
			af = mapping.findForward("miniList");
		} else if("list".equalsIgnoreCase(reqCode)){
			NewsLST lst = new NewsLST();
			lst.setLanguage(request.getParameter("language"));
			lst.setDate(request.getParameter("date"));
			if(request.getParameter("page")!=null)
				lst.setCurrentPage(NVL.getInt(request.getParameter("page")));
			try {
				lst = getDAO().getNewsLST(lst);
			} catch (AMSException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			NewsENT newsENT = new NewsENT();
			request.setAttribute("newsENT", newsENT);
			request.setAttribute("newsLST", lst);
			af = mapping.findForward("list");
		} else if("save".equalsIgnoreCase(reqCode) || "saveEdited".equalsIgnoreCase(reqCode)){
			NewsENT ent = new NewsENT();
			ent.setDate(request.getParameter("date").replace('/', '-'));
			ent.setLanguage(request.getParameter("language"));
			ent.setText(request.getParameter("text"));
			ent.setTitle(request.getParameter("title"));
			if("saveEdited".equalsIgnoreCase(reqCode)){
				ent.setId(NVL.getInt(request.getParameter("id")));
			}
			NewsLST lst = new NewsLST();
			lst.setLanguage(request.getParameter("language"));
			try {
				lst = getDAO().saveNews(ent);
			} catch (AMSException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			request.setAttribute("newsENT", ent);
			request.setAttribute("newsLST", lst);
			af = mapping.findForward("list");
		} else if("getNews".equalsIgnoreCase(reqCode)){
			int newsId = NVL.getInt(request.getParameter("id"));
			NewsENT ent = new NewsENT();
			try {
				ent = getDAO().getNewsEnt(newsId);
			} catch (AMSException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			request.setAttribute("newsENT", ent);
			af = mapping.findForward("view");
		} else if("edit".equalsIgnoreCase(reqCode)){
			int newsId = NVL.getInt(request.getParameter("id"));
			NewsENT ent = new NewsENT();
			try {
				ent = getDAO().getNewsEnt(newsId);
			} catch (AMSException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			request.setAttribute("newsENT", ent);
			af = mapping.findForward("view");
		}
		return af;
	}
	private static NewsDAOInterface getDAO() {
		return ams.ggc.common.orm.SellDAOManager.getNewsDAOInterface();
	}
}