/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ggc.struts.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ggc.Classes.NewsENT;
import com.ggc.Classes.NewsLST;
import com.ggc.Classes.tools.NVL;
import com.ggc.Classes.tools.UTF8;
import com.ggc.business.NewsBusinessManager;

/** 
 * MyEclipse Struts
 * Creation date: 09-21-2010
 * 
 * XDoclet definition:
 * @struts.action parameter="reqCode" validate="true"
 * @struts.action-forward name="list" path="/jsp/farsi/news/newsList.jsp"
 */
public class NewsAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ActionForward af = null;
		String reqCode=request.getParameter("reqCode");	
		if("miniList".equalsIgnoreCase(reqCode)){
			NewsBusinessManager bs = new NewsBusinessManager();
			NewsLST lst = new NewsLST();
			lst = bs.getNewsMiniList(request.getParameter("language"));
			request.setAttribute("newsMiniLST", lst);
			af = mapping.findForward("miniList");
		} else if("list".equalsIgnoreCase(reqCode)){
			NewsBusinessManager bs = new NewsBusinessManager();
			NewsLST lst = new NewsLST();
			lst.setLanguage(request.getParameter("language"));
			lst.setDate(request.getParameter("date"));
			if(request.getParameter("page")!=null)
				lst.setCurrentPage(NVL.getInt(request.getParameter("page")));
			lst = bs.getNewsList(lst);
			NewsENT newsENT = new NewsENT();
			request.setAttribute("newsENT", newsENT);
			request.setAttribute("newsLST", lst);
			af = mapping.findForward("list");
		} else if("save".equalsIgnoreCase(reqCode) || "saveEdited".equalsIgnoreCase(reqCode)){
			NewsBusinessManager bs = new NewsBusinessManager();
			NewsENT ent = new NewsENT();
			ent.setDate(request.getParameter("date").replace('/', '-'));
			ent.setLanguage(request.getParameter("language"));
			ent.setText(request.getParameter("text"));
			ent.setTitle(request.getParameter("title"));
			if("saveEdited".equalsIgnoreCase(reqCode)){
				ent.setId(NVL.getInt(request.getParameter("id")));
			}
			bs.insertNews(ent);
			NewsLST lst = new NewsLST();
			lst.setLanguage(request.getParameter("language"));
			lst = bs.getNewsList(lst);
			request.setAttribute("newsENT", ent);
			request.setAttribute("newsLST", lst);
			af = mapping.findForward("list");
		} else if("getNews".equalsIgnoreCase(reqCode)){
			NewsBusinessManager bs = new NewsBusinessManager();
			int newsId = NVL.getInt(request.getParameter("id"));
			NewsENT ent = new NewsENT();
			ent = bs.getNewsENT(newsId);
			request.setAttribute("newsENT", ent);
			af = mapping.findForward("view");
		} else if("edit".equalsIgnoreCase(reqCode)){
			NewsBusinessManager bs = new NewsBusinessManager();
			int newsId = NVL.getInt(request.getParameter("id"));
			NewsENT ent = new NewsENT();
			ent = bs.getNewsENT(newsId);
			request.setAttribute("newsENT", ent);
			af = mapping.findForward("view");
		}
		return af;
	}
}