/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ams.ggc.struts;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import ams.ggc.common.User.CompanyUserENT;
import ams.ggc.common.User.RealUserENT;
import ams.ggc.common.User.UserDAOInterface;
import ams.ggc.common.User.UserENT;
import ams.ggc.common.User.UserPassword;
import ams.ggc.common.tools.AMSErrorHandler;
import ams.ggc.common.tools.AMSException;


/** 
 * MyEclipse Struts
 * Creation date: 09-21-2010
 * 
 * XDoclet definition:
 * @struts.action parameter="reqCode" validate="true"
 * @struts.action-forward name="list" path="/jsp/farsi/news/newsList.jsp"
 */
public class RegisterAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ActionForward af = null;
		String reqCode=request.getParameter("reqCode");
		String error = "";
		String success = "";
		if("".equalsIgnoreCase(reqCode)||reqCode==null){
			UserENT userENT = new UserENT();
			request.setAttribute("userENT", userENT);
			af = mapping.findForward("registeration");
		}else if("save".equalsIgnoreCase(reqCode)){
			UserENT userENT = new UserENT();
			userENT = getUserENT(request);
			boolean insertResult = false;
			try {
				insertResult = getDAO().register(userENT, request.getParameter("type"));
			} catch (AMSException e) {
				e.printStackTrace();
			}
			request.setAttribute("userENT", userENT);
			if(insertResult)
				af = mapping.findForward("registerationSuccess");
			else
				af = mapping.findForward("registeration");
		}else if("checkValidity".equalsIgnoreCase(reqCode)){
			UserENT userENT = new UserENT();
			userENT = getUserENT(request);
			request.setAttribute("availability", "isNotValid");
			try {
				if(getDAO().checkUsernameValidity(userENT.getUserName())){
					request.setAttribute("availability", "isValid");
				}
			} catch (AMSException e) {
				e.printStackTrace();
			}
			request.setAttribute("userENT", userENT);
			af = mapping.findForward("registeration");
		}else if ("changePassword".equalsIgnoreCase(reqCode)){
			UserPassword password = new UserPassword();
			password.setUserPassword(request.getParameter("newPass"));
			password.setOldPassword(request.getParameter("oldPass"));
			String username = request.getParameter("username");
			System.out.println(username);
			if("null".equalsIgnoreCase(username)||username==null){
				password.setUserName(request.getRemoteUser());
			}else{
				password.setUserName(request.getParameter("username"));
			}
			try {
				getDAO().changePassword(password);
				success = "عملیات تغییر رمز با موفقیت انجام شد";
			} catch (AMSException e) {
				error = AMSErrorHandler.handle(request, this, e, "", "");
				e.printStackTrace();
			}
			af = mapping.findForward("changePasswordView");
		}else if("changePasswordView".equalsIgnoreCase(reqCode)){
			af = mapping.findForward("changePasswordView");
		}
		request.setAttribute("error", error);
		request.setAttribute("success", success);
		return af;
	}
	public UserENT getUserENT(HttpServletRequest request){
		UserENT userENT = new UserENT();
		CompanyUserENT companyUserENT = new CompanyUserENT();
		RealUserENT realUserENT = new RealUserENT();
		UserPassword password = new UserPassword();
		password.setUserName(request.getParameter("userName"));
		password.setUserPassword(request.getParameter("password"));
		userENT.setUserName(request.getParameter("userName"));
		userENT.setPassword(password);
		if("real".equalsIgnoreCase(request.getParameter("type"))){
			realUserENT.setName(request.getParameter("realUserENT.name"));
			realUserENT.setAddress(request.getParameter("realUserENT.name"));
			realUserENT.setEmailAddress(request.getParameter("realUserENT.emailAddress"));
			realUserENT.setFamilyName(request.getParameter("realUserENT.familyName"));
			realUserENT.setNationalID(request.getParameter("realUserENT.nationalID"));
			realUserENT.setTel(request.getParameter("realUserENT.tel"));
			realUserENT.setFaxNo(request.getParameter("realUserENT.faxNo"));
			realUserENT.setWebSiteAddress(request.getParameter("realUserENT.webSiteAddress"));
			realUserENT.setAddress(request.getParameter("realUserENT.address"));
			realUserENT.setDob(request.getParameter("year")+"-"+request.getParameter("month")+"-"+request.getParameter("day"));
			realUserENT.setOccupation(request.getParameter("occupation"));
			realUserENT.setUserName(request.getParameter("userName"));
		}else{
			companyUserENT.setCompanyName(request.getParameter("companyUserENT.companyName"));
			companyUserENT.setEconomicNumber(request.getParameter("companyUserENT.economicNumber"));
			companyUserENT.setTel(request.getParameter("companyUserENT.tel"));
			companyUserENT.setFaxNo(request.getParameter("companyUserENT.faxNo"));
			companyUserENT.setWebSiteAddress(request.getParameter("companyUserENT.webSiteAddress"));
			companyUserENT.setEmailAddress(request.getParameter("companyUserENT.emailAddress"));
			companyUserENT.setAddress(request.getParameter("companyUserENT.address"));
			companyUserENT.setUserName(request.getParameter("userName"));
		}
		userENT.setCompanyUserENT(companyUserENT);
		userENT.setRealUserENT(realUserENT);
		return userENT;
	}
	private static UserDAOInterface getDAO() {
		return ams.ggc.common.orm.SellDAOManager.getUserDAOInterface();
	}
}